name: 'coverage'

env:
  CI: true
  DATABASE_URL: postgresql://postgres:postgres@0.0.0.0:5432/test_db

on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v1
            - uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
              with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    threshold: 60 # optional parameter