name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI: true
  DATABASE_URL: postgresql://postgres:postgres@0.0.0.0:5432/test_db

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: ['14', '16']
        os: [ubuntu-latest]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - name: ♻️ Check out Git Repository
        uses: actions/checkout@v2

      - name: 🔖  Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: ⬇️  Install npm dependencies
        run: npm install

      - name: 🔥 Test database connection
        run: npm run test:db:connection

      - name: ✅  Run tests
        run: npm run test

      - name: 🧽 Lint all files
        run: npm run lint:check

      # - name: ⛏️ Build
      #   run: npm run build

      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          repo_token: ${{ secrets.COVERALLS_REPO_TOKEN }}