name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CI: true
  DATABASE_URL: postgresql://postgres:postgres@0.0.0.0:5432/test_db
  VITE_APP_FIREBASE_apiKey: 'placeholderTestKey'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: ['14'] # ['12', '14', '16']
        os: [ubuntu-latest]

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    steps:
      - name: ♻️ Check out Git Repository
        uses: actions/checkout@v2

      - name: 🔖  Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: ⬇️  Install npm dependencies
        run: npm install

      - name: 🔥 Test database connection
        run: npm run test:db:connection

      - name: ✅  Run tests
        run: npm run test

      - name: 🧽 Lint all files
        run: npm run lint:check

      # - name: ⛏️ Build
      #   run: npm run build

      - name: 🔮 Report test coverage
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 60 # optional parameter

      - name: 🌪️ Publish to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
